// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAv8ylrV0rdVknUniTNVWaDTu9YKzf7lo',
    appId: '1:947788747831:web:786687f8d0406aa61adbb2',
    messagingSenderId: '947788747831',
    projectId: 'the-wall-social-media-app',
    authDomain: 'the-wall-social-media-app.firebaseapp.com',
    storageBucket: 'the-wall-social-media-app.appspot.com',
    measurementId: 'G-GHCKW9VLXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdLgdtn5f3R4rVhnXIZUgok5Vk47zT5c',
    appId: '1:947788747831:android:2e5f235675de3f5c1adbb2',
    messagingSenderId: '947788747831',
    projectId: 'the-wall-social-media-app',
    storageBucket: 'the-wall-social-media-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSblEEx2nNbZTxE1iZa7f4pYf3p-UJ-nM',
    appId: '1:947788747831:ios:615c40b0e05530d11adbb2',
    messagingSenderId: '947788747831',
    projectId: 'the-wall-social-media-app',
    storageBucket: 'the-wall-social-media-app.appspot.com',
    iosClientId: '947788747831-1v9is3983cmvjih49ceggji5ee9facmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWallSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSblEEx2nNbZTxE1iZa7f4pYf3p-UJ-nM',
    appId: '1:947788747831:ios:615c40b0e05530d11adbb2',
    messagingSenderId: '947788747831',
    projectId: 'the-wall-social-media-app',
    storageBucket: 'the-wall-social-media-app.appspot.com',
    iosClientId: '947788747831-1v9is3983cmvjih49ceggji5ee9facmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWallSocialMediaApp',
  );
}
